apiVersion: v1
kind: Pod
metadata:
  name: k8plex-test-registry
  namespace: image-registry
  labels:
    name: lbl-k8plex-test-registry
spec:
  containers:
  - image: registry
    name: k8plex-test-registry
    volumeMounts:
      - name: mnt
        mountPath: /var/lib/registry
      - name: certs
        mountPath: /certs
        readOnly: true
    ports:
      - containerPort: 443
        name: http
    env:
      - name: REGISTRY_HTTP_ADDR
        value: "0.0.0.0:443"
      - name: REGISTRY_HTTP_TLS_CERTIFICATE
        value: "/certs/tls.crt"
      - name: REGISTRY_HTTP_TLS_KEY
        value: "/certs/tls.key"
  volumes:
    - name: mnt
      persistentVolumeClaim:
        claimName: pvc-image-registry
    - name: certs
      secret:
        secretName: tls-image-registry
