apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-image-registry
  labels:
    pvl: image-registry
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
#    - nfsvers=4.1
  nfs:
    server: ##NFSSERVER##
    path: /srv/vols/image_registry
