apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-registry
  labels:
    pvl: image-registry
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
  nfs:
    server: veo1.krft
    path: /srv/vols/image_registry
