apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: image-registry
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  selector:
    matchLabels:
      pvl: image-registry
